### ISSUE TITLE
GetCode_IsAlways_Passive

### ISSUE THREAD

**Issue by DmiGen** [igorageev/figma2xaml#1]
Hello,
I've installed the plugin.
Choose some layer (group, frame, component)I, but get always passive (grey) button "Get Code". 

Below given example is simplified fast to nothing.

https://www.figma.com/file/eEOj9LvRZUQgZ7EubyHeOi/proj_5_for_VS?node-id=0%3A1

Best regards

P.S. I'm not sured given link is enough to get access to the example.

**Comment by igorageev** [comment]
Select ONLY ONE layer with group, frame or component.

**Comment by igorageev** [comment]
![image](https://user-images.githubusercontent.com/17005999/145019021-de064f8c-1c67-4185-9c13-d5cdc20215ea.png)

**Comment by igorageev** [comment]
Text nodes not yet supported

**Comment by DmiGen** [comment]
Hello, Igor !

Thank you for your quick reply.

The picture you sent looks great.

My problem is that when I select any ONE element, in the example it's rectangles, I still get an inactive "Get Code" button.

Mit freundlichen Grüßen
Best regards

Dmitrij Gendler 

    On Tuesday, December 7, 2021, 12:12:16 PM GMT+1, Igor Ageev ***@***.***> wrote:  
 
 




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by igorageev** [comment]
Rectangle is not a group or a frame.
Select It  and click Control + G (Command-G).

**Comment by DmiGen** [comment]
"Select It ..." 
"Control + G" is shortcut for creating new group from selected items.
I don't undestand why the shortcut should something change.

In any case with frames and groups desired button is not active.
Besides, whether nested groups are processed nowadays ?

**Comment by igorageev** [comment]
Nested groups are handled without problems. Group can also be created through the context menu.

![create-group](https://user-images.githubusercontent.com/17005999/145207676-7f4761c8-355e-46bd-b246-5d3a907fd586.gif)
ms

**Comment by DmiGen** [comment]
It seems to be my problem was in the design the formation of the groups was rather arbitrary.
Some rectangles exist separately outside the groups.

Good job !
